declare const _default: {
    Query: {
        version: () => string;
    };
} | import("./generated/graphql").WithIndex<{
    Patch?: import("./generated/graphql").WithIndex<{
        id?: import("./generated/graphql").ResolverFn<import("./generated/graphql").ResolverTypeWrapper<string>, Partial<import("./generated/graphql").Patch>, import("./context").Context, {}> | import("./generated/graphql").StitchingResolver<import("./generated/graphql").ResolverTypeWrapper<string>, Partial<import("./generated/graphql").Patch>, import("./context").Context, {}> | undefined;
        uuid?: import("./generated/graphql").ResolverFn<import("./generated/graphql").ResolverTypeWrapper<string>, Partial<import("./generated/graphql").Patch>, import("./context").Context, {}> | import("./generated/graphql").StitchingResolver<import("./generated/graphql").ResolverTypeWrapper<string>, Partial<import("./generated/graphql").Patch>, import("./context").Context, {}> | undefined;
        data?: import("./generated/graphql").ResolverFn<import("./generated/graphql").ResolverTypeWrapper<number>[], Partial<import("./generated/graphql").Patch>, import("./context").Context, {}> | import("./generated/graphql").StitchingResolver<import("./generated/graphql").ResolverTypeWrapper<number>[], Partial<import("./generated/graphql").Patch>, import("./context").Context, {}> | undefined;
    }> | undefined;
    Query?: import("./generated/graphql").WithIndex<{
        version?: import("./generated/graphql").ResolverFn<import("./generated/graphql").Maybe<import("./generated/graphql").ResolverTypeWrapper<string>>, {}, import("./context").Context, {}> | import("./generated/graphql").StitchingResolver<import("./generated/graphql").Maybe<import("./generated/graphql").ResolverTypeWrapper<string>>, {}, import("./context").Context, {}> | undefined;
        user?: import("./generated/graphql").ResolverFn<import("./generated/graphql").Maybe<import("./generated/graphql").ResolverTypeWrapper<Partial<import("./generated/graphql").User>>>, {}, import("./context").Context, import("./generated/graphql").QueryUserArgs> | import("./generated/graphql").StitchingResolver<import("./generated/graphql").Maybe<import("./generated/graphql").ResolverTypeWrapper<Partial<import("./generated/graphql").User>>>, {}, import("./context").Context, import("./generated/graphql").QueryUserArgs> | undefined;
        viewer?: import("./generated/graphql").ResolverFn<import("./generated/graphql").Maybe<import("./generated/graphql").ResolverTypeWrapper<Partial<import("./generated/graphql").User>>>, {}, import("./context").Context, {}> | import("./generated/graphql").StitchingResolver<import("./generated/graphql").Maybe<import("./generated/graphql").ResolverTypeWrapper<Partial<import("./generated/graphql").User>>>, {}, import("./context").Context, {}> | undefined;
    }> | undefined;
    User?: import("./generated/graphql").WithIndex<{
        patches?: import("./generated/graphql").ResolverFn<import("./generated/graphql").ResolverTypeWrapper<Partial<import("./generated/graphql").Patch>>[], Partial<import("./generated/graphql").User>, import("./context").Context, {}> | import("./generated/graphql").StitchingResolver<import("./generated/graphql").ResolverTypeWrapper<Partial<import("./generated/graphql").Patch>>[], Partial<import("./generated/graphql").User>, import("./context").Context, {}> | undefined;
        id?: import("./generated/graphql").ResolverFn<import("./generated/graphql").ResolverTypeWrapper<string>, Partial<import("./generated/graphql").User>, import("./context").Context, {}> | import("./generated/graphql").StitchingResolver<import("./generated/graphql").ResolverTypeWrapper<string>, Partial<import("./generated/graphql").User>, import("./context").Context, {}> | undefined;
        username?: import("./generated/graphql").ResolverFn<import("./generated/graphql").ResolverTypeWrapper<string>, Partial<import("./generated/graphql").User>, import("./context").Context, {}> | import("./generated/graphql").StitchingResolver<import("./generated/graphql").ResolverTypeWrapper<string>, Partial<import("./generated/graphql").User>, import("./context").Context, {}> | undefined;
        firstName?: import("./generated/graphql").ResolverFn<import("./generated/graphql").Maybe<import("./generated/graphql").ResolverTypeWrapper<string>>, Partial<import("./generated/graphql").User>, import("./context").Context, {}> | import("./generated/graphql").StitchingResolver<import("./generated/graphql").Maybe<import("./generated/graphql").ResolverTypeWrapper<string>>, Partial<import("./generated/graphql").User>, import("./context").Context, {}> | undefined;
        lastName?: import("./generated/graphql").ResolverFn<import("./generated/graphql").Maybe<import("./generated/graphql").ResolverTypeWrapper<string>>, Partial<import("./generated/graphql").User>, import("./context").Context, {}> | import("./generated/graphql").StitchingResolver<import("./generated/graphql").Maybe<import("./generated/graphql").ResolverTypeWrapper<string>>, Partial<import("./generated/graphql").User>, import("./context").Context, {}> | undefined;
    }> | undefined;
}>;
export default _default;
