name: CI

on: [push]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Yarn Install
        run: yarn
      - name: Build
        run: yarn build
