name: stable

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: docker-compose
        run: docker-compose up -d
      - name: Yarn Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
